### PR TITLE
Development

### PR DESCRIPTION
**Pull request by desreedimaky**

### CODE REVIEW

**Comment by NkosinathiSeptember23** [comment]
it's nice

**Comment by Tumisang9x** [comment]
your style.css has conflicts, please review in VS

**Review by Tumisang9x — APPROVED** [review]

**Review by NompiloZondo-Dev — APPROVED** [review]

**Comment by KevinM55** [comment]
Please fix your selection choice so we do not have to greet the bot everytime we need it to appear

**Comment by desreedimaky** [comment]
@KevinM55 i have fixed it, please check it

**Comment by NompiloZondo-Dev** [comment]
great work !

**Review by NompiloZondo-Dev — APPROVED** [review]
great work !!

**Review by Tumisang9x — APPROVED** [review]

**Review by KevinM55 — APPROVED** [review]

**Pull request merged**
